#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
package_upgrade: true

users:
- name: ubuntu
  groups:
    - docker

packages:
 - apt-transport-https
 - ca-certificates
 - curl
 - gnupg-agent
 - software-properties-common
 - build-essential
 - file
 - git
 - zsh

runcmd:
  # docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  # kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  # kind
  - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-$(uname)-amd64
  - chmod +x ./kind
  - mv ./kind /usr/local/bin/kind
  # shell
  - chsh ubuntu -s /usr/bin/zsh
  # prezto
  - curl -o /home/ubuntu/install_prezto.sh https://raw.githubusercontent.com/y-o-k-o/k8s/master/zsh-env/install_prezto.sh
  - chmod +x /home/ubuntu/install_prezto.sh
  - sh -c /home/ubuntu/install_prezto.sh
  - rm /home/ubuntu/install_prezto.sh 
  - curl -o /home/ubuntu/.zshrc https://raw.githubusercontent.com/y-o-k-o/k8s/master/zsh-env/.zshrc 
  - curl -o /home/ubuntu/.p10k.zsh https://raw.githubusercontent.com/y-o-k-o/k8s/master/zsh-env/.p10k.zsh 
  - curl -o /home/ubuntu/.zprezto/runcoms/zpreztorc https://raw.githubusercontent.com/y-o-k-o/k8s/master/zsh-env/.zpreztorc 
  # stern(log tail)
  - wget -O /usr/local/bin/stern https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64
  - chmod +x /usr/local/bin/stern
  #
  - chown ubuntu:ubuntu -R /home/ubuntu
